SET NAMES 'utf8' COLLATE 'utf8_general_ci';
USE flixtrack;

LOAD DATA LOCAL INFILE './data/agency.txt' INTO TABLE agency CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' IGNORE 1 LINES;
